# Generated by Django 5.2 on 2025-05-04 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetsky', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(max_length=300)),
                ('city', models.CharField(choices=[('Cúcuta', 'Cúcuta'), ('Los Patios', 'Los Patios'), ('Villa del Rosario', 'Villa del Rosario')], max_length=50)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('delivery', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('date_creacion', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-date_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_creacion', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_creacion', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Salsa',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='fecha_creacion',
            new_name='date_creacion',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='estado',
            new_name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetsky.presentation'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetsky.product'),
        ),
    ]
