# Generated by Django 5.2 on 2025-05-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetsky', '0002_order_presentation_product_sauce_delete_salsa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_creacion',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_creacion',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='sauce',
            old_name='date_creacion',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='date_creacion',
            new_name='creation_date',
        ),
        migrations.AlterField(
            model_name='presentation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='presentations/'),
        ),
    ]
